# Generated by Django 2.0 on 2018-10-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_record', '0003_auto_20180927_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '时间段阅读数', 'verbose_name_plural': '时间段阅读数'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读数', 'verbose_name_plural': '阅读数'},
        ),
    ]
